import Footer from "./footer";
import "./globals.css";
import Header from "./navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen">
        <div className="flex flex-col h-full">
          <div className="container mx-auto max-w-screen-lg p-5b">
            <Header />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
